/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomerWishlistRouteImport } from './routes/customer-wishlist'
import { Route as CustomerOrdersRouteImport } from './routes/customer-orders'
import { Route as CustomerDashboardRouteImport } from './routes/customer-dashboard'
import { Route as ArtisanOrdersRouteImport } from './routes/artisan-orders'
import { Route as ArtisanDashboardRouteImport } from './routes/artisan-dashboard'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as CheckoutProductIdRouteImport } from './routes/checkout.$productId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerWishlistRoute = CustomerWishlistRouteImport.update({
  id: '/customer-wishlist',
  path: '/customer-wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOrdersRoute = CustomerOrdersRouteImport.update({
  id: '/customer-orders',
  path: '/customer-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/customer-dashboard',
  path: '/customer-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanOrdersRoute = ArtisanOrdersRouteImport.update({
  id: '/artisan-orders',
  path: '/artisan-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanDashboardRoute = ArtisanDashboardRouteImport.update({
  id: '/artisan-dashboard',
  path: '/artisan-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutProductIdRoute = CheckoutProductIdRouteImport.update({
  id: '/checkout/$productId',
  path: '/checkout/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/artisan-dashboard': typeof ArtisanDashboardRoute
  '/artisan-orders': typeof ArtisanOrdersRoute
  '/customer-dashboard': typeof CustomerDashboardRoute
  '/customer-orders': typeof CustomerOrdersRoute
  '/customer-wishlist': typeof CustomerWishlistRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/signup': typeof SignupRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/product/$productId': typeof ProductProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/artisan-dashboard': typeof ArtisanDashboardRoute
  '/artisan-orders': typeof ArtisanOrdersRoute
  '/customer-dashboard': typeof CustomerDashboardRoute
  '/customer-orders': typeof CustomerOrdersRoute
  '/customer-wishlist': typeof CustomerWishlistRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/signup': typeof SignupRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/product/$productId': typeof ProductProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/artisan-dashboard': typeof ArtisanDashboardRoute
  '/artisan-orders': typeof ArtisanOrdersRoute
  '/customer-dashboard': typeof CustomerDashboardRoute
  '/customer-orders': typeof CustomerOrdersRoute
  '/customer-wishlist': typeof CustomerWishlistRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/signup': typeof SignupRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/product/$productId': typeof ProductProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-dashboard'
    | '/artisan-dashboard'
    | '/artisan-orders'
    | '/customer-dashboard'
    | '/customer-orders'
    | '/customer-wishlist'
    | '/login'
    | '/order-success'
    | '/signup'
    | '/checkout/$productId'
    | '/product/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-dashboard'
    | '/artisan-dashboard'
    | '/artisan-orders'
    | '/customer-dashboard'
    | '/customer-orders'
    | '/customer-wishlist'
    | '/login'
    | '/order-success'
    | '/signup'
    | '/checkout/$productId'
    | '/product/$productId'
  id:
    | '__root__'
    | '/'
    | '/admin-dashboard'
    | '/artisan-dashboard'
    | '/artisan-orders'
    | '/customer-dashboard'
    | '/customer-orders'
    | '/customer-wishlist'
    | '/login'
    | '/order-success'
    | '/signup'
    | '/checkout/$productId'
    | '/product/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  ArtisanDashboardRoute: typeof ArtisanDashboardRoute
  ArtisanOrdersRoute: typeof ArtisanOrdersRoute
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  CustomerOrdersRoute: typeof CustomerOrdersRoute
  CustomerWishlistRoute: typeof CustomerWishlistRoute
  LoginRoute: typeof LoginRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  SignupRoute: typeof SignupRoute
  CheckoutProductIdRoute: typeof CheckoutProductIdRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-wishlist': {
      id: '/customer-wishlist'
      path: '/customer-wishlist'
      fullPath: '/customer-wishlist'
      preLoaderRoute: typeof CustomerWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-orders': {
      id: '/customer-orders'
      path: '/customer-orders'
      fullPath: '/customer-orders'
      preLoaderRoute: typeof CustomerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-dashboard': {
      id: '/customer-dashboard'
      path: '/customer-dashboard'
      fullPath: '/customer-dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan-orders': {
      id: '/artisan-orders'
      path: '/artisan-orders'
      fullPath: '/artisan-orders'
      preLoaderRoute: typeof ArtisanOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan-dashboard': {
      id: '/artisan-dashboard'
      path: '/artisan-dashboard'
      fullPath: '/artisan-dashboard'
      preLoaderRoute: typeof ArtisanDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$productId': {
      id: '/checkout/$productId'
      path: '/checkout/$productId'
      fullPath: '/checkout/$productId'
      preLoaderRoute: typeof CheckoutProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  ArtisanDashboardRoute: ArtisanDashboardRoute,
  ArtisanOrdersRoute: ArtisanOrdersRoute,
  CustomerDashboardRoute: CustomerDashboardRoute,
  CustomerOrdersRoute: CustomerOrdersRoute,
  CustomerWishlistRoute: CustomerWishlistRoute,
  LoginRoute: LoginRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  SignupRoute: SignupRoute,
  CheckoutProductIdRoute: CheckoutProductIdRoute,
  ProductProductIdRoute: ProductProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
